dist: trusty
sudo: required

language: cpp

compiler:
  - g++

branches:
  only:
  - development
  - "/feature.*/"
  - "/hotfix.*/"

addons:
  apt:
    packages:
      - python3
      - cmake
    sources: &sources
      - ubuntu-toolchain-r-test

#before_install:
#  # C++14
#  - sudo apt-get update -qq

install: 
  # C++14
  - sudo apt-get install -qq gcc-7 g++-7
  - sudo update-alternatives --install /usr/bin/g++ g++ /usr/bin/g++-7 90

script:
  - cp .travis.buildOptions.txt buildOptions.txt
  - ls
  - python3 --version
  - g++ --version
  - python3 pythonTools/mbuild.py -g make
  - make -j4
